"""
DeliberativeAgent — handles complex tasks via PlanGraph + Executor.

Cache hierarchy (fastest → slowest):
  L1  Hot plan cache   — in-process dict keyed by normalised event hash; <0.1ms
  L2  Cold episode store — ChromaDB (semantic) or flat (word-overlap); ~10-50ms
  L3  LLM plan generation — called only on full cache miss

Plan structure is generated by the LLM (structured JSON prompt);
falls back to a canonical 4-step DAG when LLM is unavailable.
"""
from __future__ import annotations

import hashlib
import json
import logging
import re
import time
from typing import Any, Callable, Coroutine, Dict, List, Optional

from ..core.planner import PlanGraph, PlanNode, PlanExecutor
from ..core.tools import ToolRegistry

logger = logging.getLogger("SOMA_V2.DELIBERATIVE")

# ── event normalisation ───────────────────────────────────────────────────────
# Strip run-specific tokens (Var_N: prefixes, bare integers, node IDs like P3/A12)
# so semantically identical tasks map to the same cache key.

_STRIP_PREFIX  = re.compile(r"^var_\d+\s*:\s*", re.IGNORECASE)
_STRIP_NUMBERS = re.compile(r"\b[A-Z]?\d+\b")          # bare digits and ID tokens like A12, P5
_NORM_AGENTS   = re.compile(r"\b(drone|rov|submersible|uav|sub)\b", re.IGNORECASE)
_NORM_ACTIONS  = re.compile(r"\b(rescue|extraction|salvage|mission)\b", re.IGNORECASE)
_NORM_SENSORS  = re.compile(r"\b(sonar|sensor|radar)\b", re.IGNORECASE)
_MULTI_SPACE   = re.compile(r"\s{2,}")

def _normalise(text: str) -> str:
    text = _STRIP_PREFIX.sub("", text)
    text = _STRIP_NUMBERS.sub("N", text)
    text = _NORM_AGENTS.sub("AGENT_UNIT", text)
    text = _NORM_ACTIONS.sub("MISSION", text)
    text = _NORM_SENSORS.sub("SENSOR", text)
    text = _MULTI_SPACE.sub(" ", text).lower().strip()
    return text

def _plan_key(text: str) -> str:
    return hashlib.md5(_normalise(text).encode()).hexdigest()[:16]


# ── LLM plan generation ──────────────────────────────────────────────────────

_PLAN_PROMPT = """\
You are a drone mission planner. Output a JSON plan for the task below.

Task: {event}
Role: {role}, Urgency: {urgency}

Available Tools:
{tools}

Memory (Relevant Historical Cases):
{memory}

Drone command syntax — embed EXACTLY one [CMD] token per step that moves a drone:
  [CMD] TAKEOFF <unit>
  [CMD] GOTO <unit> <x> <y> <z>
  [CMD] SCAN <unit> <area>
  [CMD] DEPLOY <unit> <payload>
  [CMD] LAND <unit>
  [CMD] STATUS <unit>

Unit names: B1, B2 (map to Drone1, Drone2 in simulator).
Coordinates are in metres (z negative = altitude above ground, e.g. -4).

Return ONLY valid JSON — no markdown, no extra text:
{{
  "steps": [
    {{
      "id": "s1",
      "description": "Take off drone B1. [CMD] TAKEOFF B1",
      "deps": [],
      "interrupt": false,
      "alternative": null
    }}
  ]
}}

Rules:
- 3 to 6 steps.
- deps lists IDs of steps that must complete first.
- Every movement step MUST include a [CMD] token using the syntax above.
- Set "interrupt": true only for DEPLOY steps (irreversible payload release).
- alternative is null unless you name a fallback step id.
"""

_FALLBACK_STEPS = [
    {"id": "assess",  "description": "Assess root cause, affected resources, and severity.",
     "deps": [],         "alternative": None},
    {"id": "options", "description": "Enumerate resolution options with risks and trade-offs.",
     "deps": ["assess"], "alternative": "options_alt"},
    {"id": "execute", "description": "Execute the best option with concrete resource steps.",
     "deps": ["options"], "alternative": "execute_alt"},
    {"id": "verify",  "description": "Verify resolution success and set up monitoring.",
     "deps": ["execute"], "alternative": None},
]

_HOT_CACHE_AGENT = "__plan_cache__"   # namespace in HotMemory for cross-task plan cache


# ── command injection ─────────────────────────────────────────────────────────
# Maps action keywords in step descriptions to [CMD] tokens deterministically.
# Runs after plan generation so the LLM never needs to get the syntax right.

_UNIT_RE      = re.compile(r'\b([A-Z]\d+)\b')           # e.g. A12, B4, C3
_TAKEOFF_KW   = re.compile(r'\b(takeoff|launch|ascend|lift.?off|deploy unit|activate)\b', re.I)
_GOTO_KW      = re.compile(r'\b(navigate|proceed|move|fly|travel|head to|route|transit|relocate)\b', re.I)
_LAND_KW      = re.compile(r'\b(land|descend|RTB|return to base|touch.?down|deactivate|power down)\b', re.I)
_SCAN_KW      = re.compile(r'\b(scan|sweep|survey|search area|recon|inspect|examine)\b', re.I)
_DEPLOY_KW    = re.compile(r'\b(deploy|drop|release|deliver|attach|hook)\b', re.I)
_STATUS_KW    = re.compile(r'\b(status|ping|check|verify|confirm online|health|telemetry)\b', re.I)


def _inject_commands(graph: PlanGraph, event: str) -> PlanGraph:
    """
    Post-process a PlanGraph: append [CMD] tokens to step descriptions
    that match action keywords but don't already have a [CMD] tag.
    Unit names are extracted from the event text or default to UNIT.
    """
    units = _UNIT_RE.findall(event) or ["UNIT"]
    primary = units[0]

    for node in graph.all_nodes():
        desc = node.description
        if node.command or "[CMD]" in desc or "[DELEGATE]" in desc:
            continue   # already annotated or structured — don't double-inject

        if _TAKEOFF_KW.search(desc):
            node.description = desc + f" [CMD] TAKEOFF {primary}"
        elif _LAND_KW.search(desc):
            node.description = desc + f" [CMD] LAND {primary}"
        elif _GOTO_KW.search(desc):
            node.description = desc + f" [CMD] GOTO {primary} SECTOR"
        elif _SCAN_KW.search(desc):
            node.description = desc + f" [CMD] SCAN {primary} AREA"
        elif _DEPLOY_KW.search(desc):
            node.description = desc + f" [CMD] DEPLOY {primary} PAYLOAD"
        elif _STATUS_KW.search(desc):
            node.description = desc + f" [CMD] STATUS {primary}"

    return graph


def _apply_safety_rails(graph: PlanGraph, tool_registry: Optional[Any]) -> PlanGraph:
    """
    Force interrupt=True if a step uses a tool marked as HIGH risk, 
    regardless of what the LLM decided.
    """
    if not tool_registry:
        return graph

    for node in graph.all_nodes():
        if node.command:
            tool = tool_registry.get(node.command)
            if tool and hasattr(tool, 'risk') and tool.risk == "HIGH":
                if not node.interrupt:
                    logger.warning(f"Safety Rail: Forcing interrupt on HIGH risk tool '{tool.name}'")
                    node.interrupt = True
    return graph


def _steps_to_graph(steps: List[Dict]) -> PlanGraph:
    g = PlanGraph()
    for s in steps:
        g.add_node(PlanNode(
            node_id=s["id"],
            description=s["description"],
            deps=s.get("deps") or [],
            alternative=s.get("alternative"),
            command=s.get("command"),
            interrupt=s.get("interrupt") or False,
        ))
    return g


def _graph_from_json(plan_json: str) -> Optional[PlanGraph]:
    try:
        data  = json.loads(plan_json)
        graph = _steps_to_graph(data["steps"])
        graph.topological_waves()   # validate — raises on cycle
        return graph
    except Exception as exc:
        logger.warning(f"DeliberativeAgent: cached plan invalid, discarding ({exc})")
        return None


async def _llm_plan(event: str, role: str, urgency: str, llm_callback, memory=None, tools: str = "None") -> PlanGraph:
    mem_text = "No relevant memory found."
    if memory:
        try:
            episodes = memory.recall_similar(event, n=3)
            if episodes:
                lines = []
                for ep in episodes:
                    meta    = ep.get("metadata", {})
                    suc     = "SUCCESS" if meta.get("success") else "FAILED"
                    action  = meta.get("action", "?")
                    dist    = ep.get("distance")
                    sim_str = f"sim={1-dist:.2f}" if dist is not None else "sim=high"
                    lines.append(
                        f"- [{suc}] action={action} {sim_str}: {ep['event'][:120]}"
                    )
                failed_count = sum(1 for ep in episodes if not ep.get("metadata", {}).get("success"))
                header = (
                    f"({len(episodes)} similar cases — {failed_count} failed; "
                    f"adapt plan to avoid known failure modes)"
                )
                mem_text = header + "\n" + "\n".join(lines)
        except Exception as exc:
            logger.warning(f"DeliberativeAgent: memory recall failed: {exc}")

    prompt = _PLAN_PROMPT.format(event=event[:300], role=role, urgency=urgency, memory=mem_text, tools=tools)
    try:
        raw = await llm_callback("deliberative_plan", prompt)
        # ── multi-strategy JSON extraction ───────────────────────────────────
        # Strategy 1: strip markdown fences and try directly
        cleaned = re.sub(r"```(?:json)?", "", raw).strip().rstrip("`").strip()
        # Strategy 2: extract first {...} block found anywhere in the response
        brace_match = re.search(r"\{[\s\S]*\}", cleaned)
        if brace_match:
            cleaned = brace_match.group(0)
        data  = json.loads(cleaned)
        graph = _steps_to_graph(data["steps"])
        graph.topological_waves()
        logger.info(f"DeliberativeAgent: LLM plan accepted ({len(graph)} steps)")
        return graph
    except Exception as exc:
        logger.warning(f"DeliberativeAgent: LLM plan parse failed ({exc}), using fallback")
        return _steps_to_graph(_FALLBACK_STEPS)


# ── agent ─────────────────────────────────────────────────────────────────────

class DeliberativeAgent:
    def __init__(
        self,
        llm_callback: Optional[Callable[..., Coroutine]] = None,
        memory=None,
        cold_threshold: float = 0.40,
        actuator=None,
        delegate_fn: Optional[Callable[..., Coroutine]] = None,
        blackboard=None,
        agent_id: str = "unknown",
        negotiation_broker=None,
        tool_registry: Optional[ToolRegistry] = None,
        telemetry: Optional[Any] = None,
        **kwargs,
    ):
        self.llm_callback   = llm_callback
        self.memory         = memory
        self.cold_threshold = cold_threshold
        self.actuator       = actuator
        self.delegate_fn    = delegate_fn
        self.blackboard     = blackboard
        self.agent_id       = agent_id
        self.tool_registry  = tool_registry
        self.telemetry      = telemetry
        self._executor      = PlanExecutor(
            llm_callback=llm_callback,
            task_type="deliberative",
            actuator=actuator,
            delegate_fn=delegate_fn,
            blackboard=blackboard,
            agent_id=agent_id,
            negotiation_broker=negotiation_broker,
            tool_registry=tool_registry,
            telemetry=telemetry,
        )
        self._cache_log: List[Dict[str, Any]] = []

    def get_suspended_node(self) -> Optional[Any]:
        """Returns the PlanNode currently awaiting human approval, if any."""
        return self._executor.suspended_node

    def approve(self):
        """Signals the executor to resume the suspended node."""
        self._executor.approval_event.set()

    # ── cache helpers ─────────────────────────────────────────────────────────

    def _hot_get(self, event: str) -> Optional[PlanGraph]:
        """L1: in-process plan cache — sub-millisecond lookup."""
        if not self.memory:
            return None
        key      = _plan_key(event)
        plan_json = self.memory.recall_working(_HOT_CACHE_AGENT, key)
        if plan_json:
            graph = _graph_from_json(plan_json)
            if graph:
                logger.info(f"DeliberativeAgent: L1 hot cache HIT key={key[:8]} event='{event[:50]}'")
                return graph
        return None

    def _hot_put(self, event: str, plan_json: str) -> None:
        """Store plan in L1 hot cache. TTL=1h — long enough for a session."""
        if not self.memory:
            return
        key = _plan_key(event)
        self.memory.remember(_HOT_CACHE_AGENT, key, plan_json, ttl=3600.0)
        logger.debug(f"DeliberativeAgent: L1 hot cache stored key={key[:8]}")

    def _cold_get(self, event: str) -> Optional[PlanGraph]:
        """L2: cold episode store (ChromaDB semantic or flat word-overlap)."""
        if not self.memory:
            return None
        try:
            episodes = self.memory.recall_similar(event, n=1, only_successes=True)
            if not episodes:
                return None
            ep        = episodes[0]
            dist      = ep.get("distance")        # None for flat store
            plan_json = ep["metadata"].get("plan_json")
            if not plan_json:
                return None
            # ChromaDB: require tight distance. Flat store (dist=None): trust word-overlap rank.
            if dist is not None and dist >= self.cold_threshold:
                logger.debug(f"DeliberativeAgent: L2 cold miss dist={dist:.4f} (threshold={self.cold_threshold})")
                return None
            graph = _graph_from_json(plan_json)
            if graph:
                logger.info(
                    f"DeliberativeAgent: L2 cold cache HIT "
                    f"dist={'N/A' if dist is None else f'{dist:.4f}'} "
                    f"event='{event[:50]}'"
                )
                # Promote to L1 so next lookup is instant
                self._hot_put(event, plan_json)
                return graph
        except Exception as exc:
            logger.debug(f"DeliberativeAgent: cold cache check failed: {exc}")
        return None

    # ── main handler ──────────────────────────────────────────────────────────

    async def handle(
        self,
        event: str,
        agent_role: str,
        confidence: float,
        urgency: str,
        task_id: Optional[str] = None,
    ) -> Dict[str, Any]:
        logger.info(f"DeliberativeAgent: planning for '{event[:60]}'")

        # ── L1: hot plan cache ────────────────────────────────────────────────
        graph        = self._hot_get(event)
        cached_match = graph is not None
        cache_level  = "L1-hot" if cached_match else None

        # ── L2: cold episode store ────────────────────────────────────────────
        if not graph:
            graph = self._cold_get(event)
            if graph:
                cached_match = True
                cache_level  = "L2-cold"
        
        # Apply command injection to cached plans (Priority Fix)
        if graph:
            graph = _inject_commands(graph, event)

        # ── log hit/miss (Priority 4) ─────────────────────────────────────────
        self._cache_log.append({
            "task_num": len(self._cache_log) + 1,
            "hit": cached_match,
            "level": cache_level,
            "event": event[:50],
            "timestamp": time.time()
        })

        if self.telemetry:
            self.telemetry.log_event("cache_query", {
                "hit": cached_match,
                "level": cache_level or "miss",
                "event_text": event[:50]
            })

        # ── L3: LLM plan generation ───────────────────────────────────────────
        if not graph:
            if self.llm_callback:
                tools_prompt = "None"
                if self.tool_registry:
                    tools_prompt = self.tool_registry.get_prompt()
                
                graph = await _llm_plan(
                    event, agent_role, urgency, self.llm_callback, 
                    memory=self.memory, 
                    tools=tools_prompt
                )
            else:
                graph = _steps_to_graph(_FALLBACK_STEPS)
            # Inject [CMD] tokens deterministically — LLM output is unreliable for syntax
            graph = _inject_commands(graph, event)
            graph = _apply_safety_rails(graph, self.tool_registry)

        # ── execution ─────────────────────────────────────────────────────────
        result = await self._executor.execute(graph, context=event, task_id=task_id)

        # ── cache invalidation on failure ──────────────────────────────────────
        # If we reused a cached plan and it failed, evict it so future tasks
        # fall through to LLM re-planning rather than re-using a broken plan.
        if cached_match and not result.success:
            key = _plan_key(event)
            if self.memory:
                self.memory.forget(_HOT_CACHE_AGENT, key)
                logger.warning(
                    f"DeliberativeAgent: cached plan failed — evicted L1 key={key[:8]} "
                    f"(will re-plan next time)"
                )

        logger.info(
            f"DeliberativeAgent: {result.steps_done}/{len(graph)} steps "
            f"success={result.success} cached={cache_level or 'miss'} "
            f"latency={result.total_latency_ms:.1f}ms"
        )

        done_outputs = [
            v["output"] for v in result.node_outcomes.values()
            if v["status"] == "done" and v["output"]
        ]
        rationale = done_outputs[-1] if done_outputs else result.summary
        action    = "resolve" if result.success else "escalate"

        # Serialise plan for L1 store + Director → cold memory write
        plan_json: Optional[str] = None
        if result.success and not cached_match:
            try:
                steps = [
                    {"id": n.node_id, "description": n.description,
                     "deps": n.deps, "alternative": n.alternative}
                    for n in graph.all_nodes()
                ]
                plan_json = json.dumps({"steps": steps})
                self._hot_put(event, plan_json)   # promote to L1 immediately
            except Exception as exc:
                logger.warning(f"DeliberativeAgent: plan serialisation failed: {exc}")

        return {
            "action":       action,
            "confidence":   confidence,
            "urgency":      urgency,
            "rationale":    rationale,
            "steps":        result.steps_done,
            "plan_summary": result.summary,
            "plan_detail":  result.node_outcomes,
            "metadata": {
                "cached":      cached_match,
                "cache_level": cache_level,
                "plan_json":   plan_json,   # picked up by Director → cold memory episode
            },
        }
